### PR TITLE
Pull from ponyrt 54fbf3c

### PR DESCRIPTION
**Pull request by albertnetymk**
Two identified major change:

- `pony_alloc_final` use two args, and finalizer function is specified
  in `pony_type_t`

- `hash.c` uses robin hood hash algorithm

### CODE REVIEW

**Comment by EliasC** [comment]
I've only looked at the changes to the Encore specific files, but since they look reasonable and the tests pass, I'm in favour of merging this. Will do so when someone else has also approved it.

**Comment by kikofernandez** [comment]
I am a bit skeptical to merging this before the meeting in Brussels. This PR has only been tested once and I am not even sure if someone has run all the tests on a OS X. Before this gets merged, it should be discussed (tomorrow) and tested on OS X.

**Comment by albertnetymk** [comment]
It would be good if this could be done before this month ends.

**Comment by EliasC** [comment]
@kikofernandez Are you fine with merging this now that the review is over?

**Comment by kikofernandez** [comment]
yes, you can merge this after 15.00 today

**Pull request merged**
