### PR TITLE
Fixed using future in closure's body

### PR DESCRIPTION
**Pull request by PhucVH888**
This PR fixes the issue #806 .

Here is the issue: when a future is used in the closure's body, it may causes a deadlock.

### Example 1: 
```
active class Main
  def main() : unit
    val fres = (fun (x : int) : Fut[int] => this ! inc(x))
    println("{}", get(fres(42)))
  end
  def inc(x : int) : int
    x + 1
  end
end
```
### Example 2
```
active class Main
  def main() : unit
    val fres = fun (x : int) : int => get(this ! inc(x))
    println("{}", fres(42))
  end

  def inc(x : int) : int
    x + 1
  end
end
```
The issue won't happen if the await() is used.
``
    ...
  def main() : unit
    val fres = (fun (x : int) : Fut[int] => this ! inc(x))
    val t = fres(42)
    await(t)
    println("{}", get(t))
  end
    ...
```

### CODE REVIEW

**Comment by kikofernandez** [comment]
As far as I see, this solution penalizes all calls to `get`, even the ones that would not cause deadlock. Is there any other way of dynamically checking if the call on `get` would cause deadlock and, if so, run this code that you generate?

**Comment by EliasC** [comment]
If I understand correctly, this PR inserts an implicit `await` whenever `get` is used inside a closure, and when calling a closure which returns a future. I think this is bad for several reasons: 

* First of all, it interrupts the current behavior in a way that is invisible to the programmer. An `await` means that other messages may be handled by the current actor until the future is fulfilled. In the following code, I would expect the field `fld` to stay unchanged, but since there is now an implicit `await`, I don't have that guarantee:
    ```
    active class A
      var fld : int
      def m() : unit
        val old = this.fld
        val f = fun () => get((new Foo) ! foo())
        f()
        assertTrue(this.fld == old) -- May fail!
      end
    end
    ```
    Similarly, I lose the ability to call a closure that returns a future and pass that future to someone else while continuing my work. For example, in the following code, the current actor will wait for each future to be fulfilled before sending the next one, killing all parallelism:
    ```
    def distribute(getNext : () -> Fut[int]) : unit
      for worker <- this.workers do
        val fut = getNext()
        -- Implicit barrier, where we wait for the future to be fulfilled
        worker ! work(fut)
      end
    end
    ```
* Secondly, it seems a bit ad-hoc that I get one behavior when calling a closure, and another one when calling a global function. For example, in the following code, I will have different blocking behavior when calling `foo` and when calling `f`, even though they refer to the same function:
    ```
    fun foo() : Fut[int]
      ...
    end
    fun bar() : unit
      val f = foo
      foo() -- No interruption
      f() -- Implicit await
    end
    ```
* Lastly, I'm not sure I think this is a bug in the language. If you cause a deadlock in your program, that's a programmer error, not a language issue. If we want to prevent deadlocks, we should come up with a way to get rid of them completely, not just for very specific cases like this.

**Comment by supercooldave** [comment]
I agree with @kikofernandez and @EliasC. This changes the semantics, so should be rejected.
If the problem is that you have a test case that doesn't test `forward` as you would like, why not add `await` in the test case?

**Comment by PhucVH888** [comment]
I see. Thanks for all comments. I thought it was a bug, so the fix is no longer necessary, and closed now.

**Pull request closed without merging**
