### PR TITLE
Additional Savina Benchmarks

### PR DESCRIPTION
**Pull request by supercooldave**
This PR groups together Savina benchmarks that were previously submitted, but worked only for pre-Kappa. They have been fixed and now produce minimal output so they can be used in the stress test directory.

Credit should be given to Sophia, Einar and Tobias, who wrote these (but they also let them rot).

### CODE REVIEW

**Comment by supercooldave** [comment]
Interesting. The recent array fix has resulted in an assertion failure in NQueens.
This could point to the bug Einar had trouble tracking down.

**Comment by albertnetymk** [comment]
The failure was there before the merge of `array-fix`, FYI.

**Comment by supercooldave** [comment]
@albertnetymk I knew the fix was related to arrays and the bug was related to arrays, so I put 2 and apple together and got yellow.

After looking in detail, the take away message is to every now and again run the compiler in debug mode to find more errors.

**Comment by kikofernandez** [comment]
what's the status on this? I see a commit that seems to fix the error. Let me know when this is fixed and I will review and merge this.

**Comment by supercooldave** [comment]
The bug in NQueens has been fixed.
NQueens still has the problem that it leaks memory because the bulk of the computation occurs within a single recursive method call. Running it with input 17 almost killed my machine. I'm not sure whether it is a high priority to fix the problem. I tried to using `forward`, but that revealed bugs in `forward`.

**Comment by supercooldave** [comment]
In summary, just leave this open for a little longer. I'll see if I can find time to fix.

**Review by kikofernandez — APPROVED** [review]
this looks good. Merging today at 15.00

**Pull request merged**
