### PR TITLE
Add savina benchmark 4. Fork Join Throughput

### PR DESCRIPTION
**Pull request by kikofernandez**
Add savina benchmark `4. Fork Join Throughput`

### CODE REVIEW

**Comment by kikofernandez** [comment]
I have assigned the reviewer as per [README.md in Savina](https://github.com/parapluu/encore/tree/development/src/tests/stress/savina)

**Comment by supercooldave** [comment]
Again, I don't see any joining.

**Comment by kikofernandez** [comment]
again, it's a direct translation. You should check the original code and the one produced here.
(I am not making this up, it's the given name and a direct translation)

**Comment by supercooldave** [comment]
`AkkaActorState.awaitTermination(system)`

**Comment by kikofernandez** [comment]
reading the program carefully, I understand that they send messages and need to wait until all actors have finished their work. This is implicit in Encore, as the program cannot terminate unless all actors have performed their work (copy-paste from #778 )

**Review by supercooldave — CHANGES_REQUESTED** [review]
This can be accepted, IMO, after changing the name of the directory 4.fjthrput to something more parseable, such as 4.ForkJoinThroughput.

**Comment by kikofernandez** [comment]
the reason the naming was to have the same name convention as the original code, so that it's easier to see which benchmarks we have implemented. I am happy to do the renaming.

**Comment by supercooldave** [comment]
Best not change the name then.

**Pull request merged**
