### PR TITLE
Adding recursive matrix multiplication

### PR DESCRIPTION
**Pull request by TobiasWrigstad**
Adds Savina program no 20

### CODE REVIEW

**Review by kikofernandez — APPROVED** [review]
It looks fine. Minor comment on checking the final result

**Comment by kaeluka** [comment]
Just noticed that this is being reviewed already. Un-assigning myself.

**Comment by supercooldave** [comment]
I don't know whether it's me, but I cannot access this branch to see whether it can be merged. 
git cannot find the repo: https://github.com/TobiasWrigstad/encore.git/
@TobiasWrigstad

**Comment by EliasC** [comment]
When we made the Encore repo public, all forks were disconnected from the repo (since they are private). Everyone with a fork needs to delete their old fork and re-fork the Encore repo. Local branches can be re-pushed to the new fork, so nothing needs to be discarded.

**Comment by supercooldave** [comment]
Closing as PR is broken (since going public) and out of date (not Kappa compliant).
New PR replacing this will follow soon.

**Pull request closed without merging**
