### PR TITLE
Remove C-warning when using non unit-typed loops

### LINKED ISSUE #759: Gets C warning when for loop has non-unit type
```
class Main
  def f() : int
    1
  end

  def main() : unit
    for i <- [0 .. 10] do
      this.f()
    end
  end
end
```

Compiling emits C warning `incompatible integer to pointer conversion assigning to 'void *' from 'int64_t' (aka 'long')`.

### PR DESCRIPTION
**Pull request by EliasC**
This commit gets rid of a C-warning when the body of a loop does
not have the type `unit`. No test has been added, as warning
output cannot be tested.

Fixes #759.

### CODE REVIEW

**Comment by albertnetymk** [comment]
The commit msg doesn't reflect the actual content accurately; it changes the type of all `loop` constructs.

**Comment by EliasC** [comment]
> The commit msg doesn't reflect the actual content accurately; it changes the type of all `loop` constructs.

What do you mean? All loops are already given the type `unit`. This commit just removes the generated code that assigns the result of the body to a variable. Since the result will always be interpreted as having the type `unit`, we can just return the unit value directly (as in this commit).

**Comment by albertnetymk** [comment]
My mistake; I thought loops still get the type of the last expr. Thanks for the clarification.

**Comment by albertnetymk** [comment]
Merge at 16:00 if no objections.

**Pull request merged**
